---
- name: Hostname | Update the hostname - (/etc/hostname)
  template:
    src: etc_hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  register: hostname
  tags:
    - hostname

- name: Hostname | Update the hostname (shell)
  command:
    "hostname -F /etc/hostname"
  when: hostname|changed

- name: Hostname | Update the hosts - (/etc/hosts)
  template:
    src: etc_hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - hosts